name: NanoPi-R2S RK3328 OpenWrt 19.07 Build

on:
  push:
    paths:
      - 'CHANGELOG.md'

jobs:

  build:

    runs-on: ubuntu-18.04

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get -y install unzip subversion
          sudo apt-get -y purge dotnet* ghc* google* llvm* mysql* php* zulu* firefox hhvm
          sudo apt-get -y autoremove --purge          
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash

      #- name: Setup Debug Session
      #  uses: P3TERX/debugger-action@master
  
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Download Source
        run: |
          rm -rf code
          mkdir code
          cd code
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.5 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          cp ../rk3328.xml ../code/.repo/manifests/rk3328.xml
          repo sync -c --no-clone-bundle -j8

      - name: Install Extra Packages
        run: |
          cd code/friendlywrt/package

          # 广告助手，暂时关闭
          # git clone https://github.com/rufengsuixing/luci-app-adguardhome

          # OpenClash
          svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash

          # ddns-scripts_dnspod
          svn co https://github.com/coolsnowwolf/lede/trunk/package/lean/ddns-scripts_dnspod

          # frps
          git clone https://github.com/kuoruan/openwrt-frp.git frp


      - name: Update Target.mk
        run: |
          cd code/friendlywrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Update Feeds		
        run: |		
          cd code/friendlywrt		
          ./scripts/feeds update -a		
          ./scripts/feeds install -a

      - name: Install Mods
        run: |
          cd code/friendlywrt

          # openclash依赖项
          rm -rf feeds/packages/libs/libcap
          svn co https://github.com/openwrt/openwrt/trunk/package/libs/libcap feeds/packages/libs/libcap

          # rm -rf feeds/packages/libs/libnatpmp
          # svn co https://github.com/coolsnowwolf/packages/trunk/libs/libnatpmp feeds/packages/libs/libnatpmp
          
          # rm -rf feeds/packages/lang/luasec
          # svn co https://github.com/coolsnowwolf/packages/trunk/lang/luasec feeds/packages/lang/luasec

          # sed -i '/STAMP_BUILT/d' feeds/packages/utils/runc/Makefile
          # sed -i '/STAMP_BUILT/d' feeds/packages/utils/containerd/Makefile
          
          # sed -i '/upx/d' package/lean/frp/Makefile
          # sed -i '/upx/d' package/lean/UnblockNeteaseMusicGo/Makefile
          # sed -i '/upx/d' package/trojan-go/Makefile

          # 404了
          # wget -O package/kernel/kmod-sched-cake/Makefile https://raw.githubusercontent.com/coolsnowwolf/lede/master/package/kernel/kmod-sched-cake-oot/Makefile
          # wget -O feeds/packages/libs/libxml2/Makefile https://raw.githubusercontent.com/coolsnowwolf/packages/master/libs/libxml2/Makefile

          # sed -i "/redirect_https/d" package/network/services/uhttpd/files/uhttpd.config
          # sed -i '/Load Average/i\\t\t<tr><td width="33%"><%:CPU Temperature%></td><td><%=luci.sys.exec("cut -c1-2 /sys/class/thermal/thermal_zone0/temp")%><span>&#8451;</span></td></tr>' feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          # sed -i 's/pcdata(boardinfo.system or "?")/"ARMv8"/' feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          # sed -i 's/services/vpn/g' package/feeds/luci/luci-app-openvpn/luasrc/controller/openvpn.lua
          # sed -i 's/resolv.conf.d\/resolv.conf.auto/resolv.conf.auto/g' package/lean/luci-app-flowoffload/root/etc/init.d/flowoffload

          # 这里是给docker准备的
          # sed -i '/done/imkfs.ext4 /dev/mmcblk0p2 && mkdir /mnt/mmcblk0p2 && mount /dev/mmcblk0p2 /mnt/mmcblk0p2 && mkdir /mnt/mmcblk0p2/docker\n' package/base-files/files/root/setup.sh
          # sed -i "/done/iblock detect | sed \"s/enabled\\\t'0'/enabled\\\t'1'/\" > /etc/config/fstab\n" package/base-files/files/root/setup.sh
          # sed -i '/done/i[ -f /etc/init.d/dockerman ] && /etc/init.d/dockerman restart\n' package/base-files/files/root/setup.sh

          # sed -i 's/\/opt\/docker/\/mnt\/mmcblk0p2\/docker/g' package/luci-app-dockerman/root/etc/config/dockerman
          # sed -i 's/\/root/\/mnt\/mmcblk0p2/g' package/luci-app-r2sflasher/root/usr/bin/rom_flash

      - name: Patch Kernel
        run: |
          cd code/kernel/
          #git apply ../../patches/001-add-full_cone_nat.patch
          git apply ../../patches/network_led_opt/*.patch

      - name: Custom Configure Files
        run: |
          rm -f code/friendlywrt/.config*
          cp r2s-rk3328-config code/configs/config_rk3328

      - name: Install UPX
        run: |
          ln -s /usr/bin/upx-ucl code/friendlywrt/staging_dir/host/bin/upx

      - name: Build OpenWrt
        run: |
          cd code
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Fix Rootfs Owner and Group
        run: |
          sudo df -lh

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/

          cp code/out/*.img.zip ./artifact/
          cp code/friendlywrt/.config ./artifact/

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S RK3328 v19.07
          path: ./artifact/
